[package]
name="web"
authors=["David J. Pearce"]
version="0.3.2"

[build]
platforms=["whiley","js"]
library=true

[build.whiley]
source="src/whiley"

[build.js]
includes=["src/js/**/*.js"]

[dependencies]
std="0.3.2"
js="0.1.7"
dom="0.2.2"
